# Generated by Django 4.2.7 on 2024-03-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapi', '0002_remove_booking_name_booking_created_at_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
