# Generated by Django 4.2.7 on 2024-03-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapi', '0004_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_info',
            field=models.CharField(default='', max_length=255),
        ),
    ]
