# Generated by Django 4.2.7 on 2024-03-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapi', '0005_booking_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='people_no',
            field=models.CharField(default='', max_length=10),
        ),
    ]
