# Generated by Django 4.2.7 on 2024-03-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapi', '0006_booking_people_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
